export const tasks = [
  {
    id: "1",
    task: "Fix the Internet Issue",
    user: "Shubham",
    dueDate: "2024-11-13",
    priority: "Normal",
    status: "Pending",
  },
  //   {
  //     id: "2",
  //     task: "Fix the Internet Issue",
  //     user: "Shubham",
  //     dueDate: "2024-11-13",
  //     priority: "Normal",
  //     status: "Pending",
  //   },
  //   {
  //     id: "3",
  //     task: "Fix the Internet Issue",
  //     user: "Shubham",
  //     dueDate: "2024-11-13",
  //     priority: "Normal",
  //     status: "Pending",
  //   },
  //   {
  //     id: "4",
  //     task: "Fix the Internet Issue",
  //     user: "Shubham",
  //     dueDate: "2024-11-13",
  //     priority: "Normal",
  //     status: "Pending",
  //   },
  //   {
  //     id: "5",
  //     task: "Fix the Internet Issue",
  //     user: "Shubham",
  //     dueDate: "2024-11-13",
  //     priority: "Normal",
  //     status: "Pending",
  //   },
  //   {
  //     id: "6",
  //     task: "Fix the Internet Issue",
  //     user: "Shubham",
  //     dueDate: "2024-11-13",
  //     priority: "Normal",
  //     status: "Pending",
  //   },
  //   {
  //     id: "7",
  //     task: "Fix the Internet Issue",
  //     user: "Shubham",
  //     dueDate: "2024-11-13",
  //     priority: "Normal",
  //     status: "Pending",
  //   },
];
