import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import TSidebar from "@/components/TSidebar";
import Navbar from "@/components/Navarbar";
import { Toaster } from "@/components/ui/toaster";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen h-screen overflow-hidden flex flex-col">
        <SidebarProvider>
          <Toaster />
          <TSidebar />
          <div className="md:block w-full">
            <Navbar />
            <div className="p-8 overflow-scroll w-full">
              <SidebarTrigger />
              {children}
            </div>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
